package gui;

import data.Group;
import data.Subgroup;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ivan
 */
public class GroupConfig extends javax.swing.JDialog {

    int day;
    utils.IndexDispatcher indexDispatcher;

    private Group group;
    private final DefaultListModel allSubgroups;

    /**
     * Creates new form SubgroupConfig
     *
     * @param parent
     * @param modal
     * @param day
     * @param indexDispatcher
     * @param group
     * @param allSubgroups
     */
    public GroupConfig(java.awt.Frame parent, boolean modal, int day, utils.IndexDispatcher indexDispatcher, Group group, DefaultListModel allSubgroups) {
        super(parent, modal);
        initComponents();

        this.day = day;
        this.indexDispatcher = indexDispatcher;

        this.group = group;

        this.allSubgroups = new DefaultListModel();
        for (int i = 0; i < allSubgroups.size(); i++) {
            boolean isPresence = false;

            for (int j = 0; j < group.getSubgroupsAsStringArray().length; j++) {
                if (allSubgroups.get(i).toString().equals(group.getSubgroupsAsStringArray()[j])) {
                    isPresence = true;
                    break;
                }
            }

            if (!isPresence) {
                this.allSubgroups.addElement(allSubgroups.get(i));
            }
        }

        allSgrp.setModel(this.allSubgroups);
        addedSgrp.setModel(this.group.getSubgroupsAsTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        addedSgrp = new javax.swing.JTable();
        delSgrpBtn = new javax.swing.JButton();
        addSgrp = new javax.swing.JButton();
        upSgrp = new javax.swing.JButton();
        dwnSgrp = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        allSgrp = new javax.swing.JList();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel18.setText("Добавлены:");

        addedSgrp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        addedSgrp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane16.setViewportView(addedSgrp);

        delSgrpBtn.setText(">");
        delSgrpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delSgrpBtnActionPerformed(evt);
            }
        });

        addSgrp.setText("<");
        addSgrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSgrpActionPerformed(evt);
            }
        });

        upSgrp.setText("^");
        upSgrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upSgrpActionPerformed(evt);
            }
        });

        dwnSgrp.setText("v");
        dwnSgrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dwnSgrpActionPerformed(evt);
            }
        });

        allSgrp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane10.setViewportView(allSgrp);

        jLabel16.setText("Все подгруппы:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upSgrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delSgrpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addSgrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dwnSgrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(addSgrp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delSgrpBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upSgrp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dwnSgrp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(jScrollPane10))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addSgrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSgrpActionPerformed
        // add subgroup to group

        /*
        1) добавить выбранный элемент в addedSubgroupsTable
        2) удалить выбранный элемент из allListSubgroups
        3) подгрузить измененную модель для addedSubgroupsTable
         */
        int selectedSubgroup = allSgrp.getSelectedIndex();

        if (selectedSubgroup != -1 && group.getSubgroupCount() < 8) {
            // 1
            group.addSubgroup(new Subgroup(((Subgroup) allSubgroups.get(selectedSubgroup)).getName(), indexDispatcher.getNextFreeIndex(day), null));
            // 2
//            DefaultListModel dlm = new DefaultListModel();
//
//            for (int i = 0; i < allSgrp.getModel().getSize(); i++) {
//                dlm.addElement(allSgrp.getModel().getElementAt(i));
//            }
//
//            dlm.remove(selectedSubgroup);
//            allSgrp.setModel(dlm);
            allSubgroups.remove(selectedSubgroup);
            // 3
            addedSgrp.setModel(group.getSubgroupsAsTableModel());
        }
    }//GEN-LAST:event_addSgrpActionPerformed

    private void delSgrpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delSgrpBtnActionPerformed
        // remove subgroup from group

        /*
        1) добавить выбранный элемент в allListSubgroups
        2) удалить выбранный элемент из addedSubgroupsTable (не сдвигая остальные) | отпускаем занятый индекс подгруппы
        3) подгрузить измененную модель для addedSubgroupsTable
         */
        if (addedSgrp.getSelectedColumn() != -1 && group.getSubgroupCount() > 0) {
            // 1
//            DefaultListModel dlm = new DefaultListModel();
//
//            for (int i = 0; i < allSgrp.getModel().getSize(); i++) {
//                dlm.addElement(allSgrp.getModel().getElementAt(i));
//            }

            allSubgroups.addElement(addedSgrp.getModel().getValueAt(addedSgrp.getSelectedRow(), 0));
            //allSgrp.setModel(dlm);
            // 2
            //group.getSubgroup(addedSgrp.getSelectedRow()).setIndex(0);
            int subgroupIndex = Integer.parseInt(group.getSubgroup(addedSgrp.getSelectedRow()).getIndex());
            indexDispatcher.releaseIndex(day, subgroupIndex);

            group.removeSubgroup(addedSgrp.getSelectedRow());
            // 3
            addedSgrp.setModel(group.getSubgroupsAsTableModel());
        }
    }//GEN-LAST:event_delSgrpBtnActionPerformed

    private void upSgrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upSgrpActionPerformed

        int selectedIndex = addedSgrp.getSelectedRow();

        if (selectedIndex > 0) {
            group.upSubroup(addedSgrp.getSelectedRow());
            addedSgrp.setModel(group.getSubgroupsAsTableModel());

            addedSgrp.setRowSelectionInterval(selectedIndex - 1, selectedIndex - 1);
        }
    }//GEN-LAST:event_upSgrpActionPerformed

    private void dwnSgrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dwnSgrpActionPerformed

        int selectedIndex = addedSgrp.getSelectedRow();

        if (selectedIndex < 7) {
            group.downSubroup(addedSgrp.getSelectedRow());
            addedSgrp.setModel(group.getSubgroupsAsTableModel());

            addedSgrp.setRowSelectionInterval(selectedIndex + 1, selectedIndex + 1);
        }

    }//GEN-LAST:event_dwnSgrpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSgrp;
    private javax.swing.JTable addedSgrp;
    private javax.swing.JList<String> allSgrp;
    private javax.swing.JButton delSgrpBtn;
    private javax.swing.JButton dwnSgrp;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JButton upSgrp;
    // End of variables declaration//GEN-END:variables
}
