package gui;

import data.Constructor;
import models.ConstructorTableModel;
import data.Regular;
import exceptions.EmptyDataException;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author ivan
 */
public class MainFrame extends javax.swing.JFrame {

    // constructor data
    private Regular regular;
    private Constructor constructor;

    /**
     * Creates new form MainFrame
     */
    private String picturePath = "";
    private ImageIcon blankPicture;

    TreePath pathForLocation;

    public MainFrame() {
        
        try {
            regular = new Regular();
            constructor = new Constructor(regular);
        } catch (EmptyDataException e) {
            System.err.println(e.getMessage());
            System.exit(1);
        }

        try {
            blankPicture = new ImageIcon(ImageIO.read(getClass().getResource("/resources/blank.png")));
        } catch (IOException e) {
            System.err.println("open blank image failed... \n" + e.getMessage());
        }

        initComponents();

        jLayeredPane1.setLayer(groupPanel, 0, 0);
        jLayeredPane1.setLayer(subgroupPanel, 0, 1);
        jLayeredPane1.setLayer(productPanel, 0, 2);
        jLayeredPane1.setLayer(termsPanel, 0, 3);
        jLayeredPane1.setLayer(constructorPanel, 0, 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        groupPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grpList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        grpTF = new javax.swing.JTextField();
        grpAddBtn = new javax.swing.JButton();
        grpMessageLabel = new javax.swing.JLabel();
        grpDelBtn = new javax.swing.JButton();
        grpTF1 = new javax.swing.JTextField();
        subgroupPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sgrpList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sgrpTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sgrpAddBtn = new javax.swing.JButton();
        sgrpDelBtn = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        sgrpTable = new javax.swing.JTable();
        sgrpTF1 = new javax.swing.JTextField();
        sgrpMsgLabel = new javax.swing.JLabel();
        productPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        prodList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        prodNameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        prodPluTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        prodPicPanel = new javax.swing.JPanel();
        prodAddBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        prodDelBtn = new javax.swing.JButton();
        prodMsgLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        prodTable = new javax.swing.JTable();
        termsPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        termsList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        termsNameTF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        termsAddBtn = new javax.swing.JButton();
        termsDelBtn = new javax.swing.JButton();
        termsMsgLabel = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        termsAddedList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        termsAllList = new javax.swing.JList();
        constructorPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        constrConfigurationTree = new javax.swing.JTree();
        constrTermGrpComboBox = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        constrDayOfWeekList = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        constrMonitor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadToServerItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Touch Builder v2.0");
        setMinimumSize(new java.awt.Dimension(924, 614));

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Группы продуктов", "Подгруппы  продуктов", "Продукты", "Кассы", "Конструктор терминалов" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setToolTipText("");
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);
        jList1.setSelectedIndex(0);

        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(732, 593));

        groupPanel.setPreferredSize(new java.awt.Dimension(732, 593));

        jLabel1.setText("Все группы:");

        jScrollPane2.setPreferredSize(new java.awt.Dimension(230, 560));
        jScrollPane2.setRequestFocusEnabled(false);

        grpList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        grpList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                grpListFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                grpListFocusLost(evt);
            }
        });
        grpList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                grpListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(grpList);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Создание новой группы"));
        jPanel2.setPreferredSize(new java.awt.Dimension(484, 458));

        jLabel2.setText("Название:");

        grpTF.setDocument(new utils.LimitedDocument(14));
        grpTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                grpTFFocusGained(evt);
            }
        });

        grpAddBtn.setText("Добавить");
        grpAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpAddBtnActionPerformed(evt);
            }
        });

        grpMessageLabel.setForeground(java.awt.Color.red);

        grpDelBtn.setText("Удалить");
        grpDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpDelBtnActionPerformed(evt);
            }
        });

        grpTF1.setDocument(new utils.LimitedDocument(18));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grpMessageLabel)
                                    .addComponent(grpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 244, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(grpAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(grpDelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(grpTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(grpTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(grpAddBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grpDelBtn)
                    .addComponent(grpMessageLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout groupPanelLayout = new javax.swing.GroupLayout(groupPanel);
        groupPanel.setLayout(groupPanelLayout);
        groupPanelLayout.setHorizontalGroup(
            groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        groupPanelLayout.setVerticalGroup(
            groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addGroup(groupPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        subgroupPanel.setPreferredSize(new java.awt.Dimension(732, 593));

        jLabel4.setText("Все подгруппы:");

        jScrollPane3.setPreferredSize(new java.awt.Dimension(230, 560));
        jScrollPane3.setRequestFocusEnabled(false);

        sgrpList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sgrpList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sgrpListFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sgrpListFocusLost(evt);
            }
        });
        sgrpList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sgrpListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(sgrpList);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Создание новой подгруппы"));
        jPanel1.setPreferredSize(new java.awt.Dimension(484, 581));

        jLabel3.setText("Название:");

        sgrpTF.setDocument(new utils.LimitedDocument(12));
        sgrpTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sgrpTFFocusGained(evt);
            }
        });

        jLabel6.setText("Членство в группах:");

        sgrpAddBtn.setText("Добавить");
        sgrpAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgrpAddBtnActionPerformed(evt);
            }
        });

        sgrpDelBtn.setText("Удалить");
        sgrpDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgrpDelBtnActionPerformed(evt);
            }
        });

        sgrpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sgrpTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sgrpTable.getTableHeader().setResizingAllowed(false);
        sgrpTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(sgrpTable);

        sgrpTF1.setDocument(new utils.LimitedDocument(18));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 268, Short.MAX_VALUE)
                        .addComponent(sgrpDelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sgrpAddBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sgrpTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(sgrpTF1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sgrpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sgrpTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgrpAddBtn)
                    .addComponent(sgrpDelBtn))
                .addContainerGap())
        );

        sgrpMsgLabel.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout subgroupPanelLayout = new javax.swing.GroupLayout(subgroupPanel);
        subgroupPanel.setLayout(subgroupPanelLayout);
        subgroupPanelLayout.setHorizontalGroup(
            subgroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subgroupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subgroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sgrpMsgLabel))
        );
        subgroupPanelLayout.setVerticalGroup(
            subgroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subgroupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subgroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(subgroupPanelLayout.createSequentialGroup()
                        .addGroup(subgroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(sgrpMsgLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        productPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        productPanel.setPreferredSize(new java.awt.Dimension(732, 593));

        jLabel7.setText("Все товары:");

        jScrollPane6.setPreferredSize(new java.awt.Dimension(230, 560));

        prodList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        prodList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prodListFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodListFocusLost(evt);
            }
        });
        prodList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                prodListValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(prodList);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Создание нового товара"));

        jLabel9.setText("Название:");

        prodNameTextField.setDocument(new utils.LimitedDocument(25));

        jLabel10.setText("PLU:");

        prodPluTextField.setDocument(new utils.LimitedDocument(8, new utils.MyDocumentFilter()));

        jLabel11.setText("Изображение:");

        prodPicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prodPicPanel.setForeground(java.awt.Color.white);
        prodPicPanel.setPreferredSize(new java.awt.Dimension(200, 112));
        prodPicPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodPicPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout prodPicPanelLayout = new javax.swing.GroupLayout(prodPicPanel);
        prodPicPanel.setLayout(prodPicPanelLayout);
        prodPicPanelLayout.setHorizontalGroup(
            prodPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        prodPicPanelLayout.setVerticalGroup(
            prodPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        prodAddBtn.setText("Добавить");
        prodAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodAddBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Членство в подгруппах:");

        prodDelBtn.setText("Удалить");
        prodDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodDelBtnActionPerformed(evt);
            }
        });

        prodMsgLabel.setForeground(java.awt.Color.red);

        prodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(prodTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prodNameTextField)
                                .addComponent(jLabel10)
                                .addComponent(prodPluTextField)
                                .addComponent(jLabel11)
                                .addComponent(prodPicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(prodMsgLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 86, Short.MAX_VALUE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(prodDelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prodAddBtn)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prodNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prodPluTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(8, 8, 8)
                        .addComponent(prodPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(prodMsgLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodAddBtn)
                    .addComponent(prodDelBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        termsPanel.setPreferredSize(new java.awt.Dimension(732, 593));

        jLabel24.setText("Группы касс:");

        jScrollPane12.setPreferredSize(new java.awt.Dimension(230, 560));

        termsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        termsList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                termsListFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                termsListFocusLost(evt);
            }
        });
        termsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                termsListValueChanged(evt);
            }
        });
        jScrollPane12.setViewportView(termsList);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Создание кассовой группы"));
        jPanel4.setPreferredSize(new java.awt.Dimension(484, 581));

        jLabel25.setText("Название:");

        jLabel26.setText("Номера касс в группе:");

        termsAddBtn.setText("Добавить группу");
        termsAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termsAddBtnActionPerformed(evt);
            }
        });

        termsDelBtn.setText("Удалить группу");
        termsDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termsDelBtnActionPerformed(evt);
            }
        });

        termsMsgLabel.setForeground(java.awt.Color.red);

        jScrollPane11.setViewportView(termsAddedList);

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        termsAllList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "001", "002", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012", "013", "014", "015", "016", "017", "018", "019", "020", "021", "022", "023", "024", "025", "026", "027", "028", "029", "030", "031", "032", "033", "034", "035", "036", "037", "038", "039", "040", "041", "042", "043", "044", "045", "046", "047", "048", "049", "050", "051", "052", "053", "054", "055", "056", "057", "058", "059", "060", "061", "062", "063", "064", "065", "066", "067", "068", "069", "070", "071", "072", "073", "074", "075", "076", "077", "078", "079", "080", "081", "082", "083", "084", "085", "086", "087", "088", "089", "090", "091", "092", "093", "094", "095", "096", "097", "098", "099", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(termsAllList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 166, Short.MAX_VALUE)
                                .addComponent(termsDelBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(termsAddBtn))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(termsNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(78, 78, 78)
                                .addComponent(termsMsgLabel))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(termsNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addComponent(termsMsgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termsAddBtn)
                    .addComponent(termsDelBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout termsPanelLayout = new javax.swing.GroupLayout(termsPanel);
        termsPanel.setLayout(termsPanelLayout);
        termsPanelLayout.setHorizontalGroup(
            termsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(termsPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(termsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        termsPanelLayout.setVerticalGroup(
            termsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(termsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(termsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(termsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        constructorPanel.setPreferredSize(new java.awt.Dimension(732, 593));

        constrConfigurationTree.setLargeModel(true);
        constrConfigurationTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                constrConfigurationTreeValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(constrConfigurationTree);

        constrTermGrpComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constrTermGrpComboBoxActionPerformed(evt);
            }
        });

        jLabel22.setText("Группа терминалов:");

        jLabel27.setText("Дни недели:");

        constrDayOfWeekList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        constrDayOfWeekList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        constrDayOfWeekList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                constrDayOfWeekListValueChanged(evt);
            }
        });
        jScrollPane14.setViewportView(constrDayOfWeekList);

        jScrollPane7.setPreferredSize(new java.awt.Dimension(250, 216));

        jTextPane1.setEditable(false);
        jTextPane1.setFocusable(false);
        jScrollPane7.setViewportView(jTextPane1);

        jButton2.setText("Редактировать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        constrMonitor.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout constrMonitorLayout = new javax.swing.GroupLayout(constrMonitor);
        constrMonitor.setLayout(constrMonitorLayout);
        constrMonitorLayout.setHorizontalGroup(
            constrMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        constrMonitorLayout.setVerticalGroup(
            constrMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setText("Кассы:");

        javax.swing.GroupLayout constructorPanelLayout = new javax.swing.GroupLayout(constructorPanel);
        constructorPanel.setLayout(constructorPanelLayout);
        constructorPanelLayout.setHorizontalGroup(
            constructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(constructorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(constructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(constructorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(constrTermGrpComboBox, 0, 245, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(269, 269, 269))
                    .addGroup(constructorPanelLayout.createSequentialGroup()
                        .addGroup(constructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(constructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(constructorPanelLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(constrMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        constructorPanelLayout.setVerticalGroup(
            constructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(constructorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(constructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(constrTermGrpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(constructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(constructorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane14))
                    .addGroup(constructorPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(constrMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLayeredPane1.setLayer(groupPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(subgroupPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(productPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(termsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(constructorPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(subgroupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(constructorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(termsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(subgroupPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(constructorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(productPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(termsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileMenu.setText("Файл");

        loadToServerItem.setText("Загрузка на сервер");
        loadToServerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadToServerItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadToServerItem);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Правка");
        jMenuBar1.add(editMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (!evt.getValueIsAdjusting()) {
            switch (jList1.getSelectedIndex()) {
                case 0: // groups
                    grpList.setModel(regular.getGroupsAsListModel());
                    jLayeredPane1.moveToFront(groupPanel);
                    break;
                case 1: // subgroups
                    sgrpList.setModel(regular.getSubgroupsAsListModel());
                    sgrpTable.setModel(regular.getGroupsAsTableModel(-1));
                    sgrpTable.getColumnModel().getColumn(0).setMaxWidth(30);

                    jLayeredPane1.moveToFront(subgroupPanel);
                    break;
                case 2: // products
                    prodList.setModel(regular.getProductsAsListModel());
                    prodTable.setModel(regular.getSubgroupsAsTableModel(-1));
                    prodTable.getColumnModel().getColumn(0).setMaxWidth(30);

                    jLayeredPane1.moveToFront(productPanel);
                    break;
                case 3: // teeminals
                    termsList.setModel(regular.getTerminalGroupsAsListModel());
                    jLayeredPane1.moveToFront(termsPanel);
                    break;
                case 4: // constructor
                    constrTermGrpComboBox.setModel(constructor.getAllTerminalGroupsAsComboBoxModel());
                    jLayeredPane1.moveToFront(constructorPanel);

                    if (constrTermGrpComboBox.getModel().getSize() > 0) {
                        constrTermGrpComboBox.setSelectedIndex(0);
                    }
                    break;
            }
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void grpAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpAddBtnActionPerformed
        // Add Group
        grpMessageLabel.setText("");

        if (grpTF.getText().isEmpty()) {
            grpMessageLabel.setText("Введите имя группы!");
        } else {

            for (int i = 0; i < regular.getGroupsCount(); i++) {
                if (regular.getGroup(i).toString().equals(grpTF.getText().trim() + " " + grpTF1.getText().trim())) {
                    grpMessageLabel.setText("Группа с таким названием уже существует!");
                    return;
                }
            }

            regular.addGroup(grpTF.getText().trim() + "::" + grpTF1.getText().trim());
            grpList.setModel(regular.getGroupsAsListModel());
            grpTF.setText("");
            grpTF1.setText("");
        }
    }//GEN-LAST:event_grpAddBtnActionPerformed

    private void grpDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpDelBtnActionPerformed
        // Del Group
        grpMessageLabel.setText("");

        if (grpList.getSelectedIndex() == -1) {
            grpMessageLabel.setText("Выберите группу!");
        } else {
            regular.removeGroup(grpList.getSelectedIndex());
            grpList.setModel(regular.getGroupsAsListModel());
            grpTF.setText("");
            grpTF1.setText("");
        }
    }//GEN-LAST:event_grpDelBtnActionPerformed

    private void grpListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grpListFocusGained
        grpMessageLabel.setText("");
    }//GEN-LAST:event_grpListFocusGained

    private void grpTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grpTFFocusGained
        grpMessageLabel.setText("");
    }//GEN-LAST:event_grpTFFocusGained

    private void sgrpAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgrpAddBtnActionPerformed
        // Add Subgroup
        sgrpMsgLabel.setText("");

        if (sgrpTF.getText().isEmpty()) {
            sgrpMsgLabel.setText("Введите имя подргуппы!");
        } else if (!((ConstructorTableModel) sgrpTable.getModel()).isAnyChecked()) {
            sgrpMsgLabel.setText("Установите членство в группе(ах)!");
        } else {

            for (int i = 0; i < regular.getSubgroupsCount(); i++) {
                if (regular.getSubgroup(i).toString().equals(sgrpTF.getText().trim() + " " + sgrpTF1.getText().trim())) {
                    return;
                }
            }

            regular.addSubgroup(sgrpTF.getText().trim() + "::" + sgrpTF1.getText().trim(),
                    ((ConstructorTableModel) sgrpTable.getModel()).getSelectedData());
            sgrpList.setModel(regular.getSubgroupsAsListModel());

            sgrpTF.setText("");
            sgrpTF1.setText("");
            sgrpMsgLabel.setText("");
            sgrpTable.getSelectionModel().clearSelection();
            ((ConstructorTableModel) sgrpTable.getModel()).clearSelection();
            sgrpTable.updateUI();
        }
    }//GEN-LAST:event_sgrpAddBtnActionPerformed

    private void sgrpDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgrpDelBtnActionPerformed
        //Del Subgroup
        sgrpMsgLabel.setText("");

        if (sgrpList.getSelectedIndex() == -1) {
            sgrpMsgLabel.setText("Выберите подгруппу!");
        } else {
            regular.removeSubgroup(sgrpList.getSelectedIndex());
            sgrpList.setModel(regular.getSubgroupsAsListModel());

            sgrpTF.setText("");
            sgrpMsgLabel.setText("");
            sgrpTable.getSelectionModel().clearSelection();
            ((ConstructorTableModel) sgrpTable.getModel()).clearSelection();
            sgrpTable.updateUI();
        }
    }//GEN-LAST:event_sgrpDelBtnActionPerformed

    private void sgrpTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sgrpTFFocusGained
        sgrpMsgLabel.setText("");
    }//GEN-LAST:event_sgrpTFFocusGained

    private void prodAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodAddBtnActionPerformed
        // Add product
        prodMsgLabel.setText("");

        if (prodNameTextField.getText().isEmpty() || prodPluTextField.getText().isEmpty()) {
            prodMsgLabel.setText("Введите Название и PLU продукта!");
        } 
//        else if (picturePath.isEmpty()) {
//            //prodMsgLabel.setText("Выберите изображение для продукта!");
//            
//        } 
        else if (!((ConstructorTableModel) prodTable.getModel()).isAnyChecked()) {
            prodMsgLabel.setText("Установите членство в подгруппе(ах)!");
        } else {
            regular.addProduct(prodNameTextField.getText(), prodPluTextField.getText(), picturePath, ((ConstructorTableModel) prodTable.getModel()).getSelectedData());
            prodList.setModel(regular.getProductsAsListModel());

            prodNameTextField.setText("");
            prodPluTextField.setText("");
            picturePath = "";
            prodPicPanel.getGraphics().drawImage(blankPicture.getImage(), 1, 1, 198, 110, prodPicPanel);
            ((ConstructorTableModel) prodTable.getModel()).clearSelection();
            prodTable.updateUI();
        }
    }//GEN-LAST:event_prodAddBtnActionPerformed

    private void prodPicPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodPicPanelMouseClicked
        // choose product picture
        ImageIcon picture;

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("./"));
        fileChooser.setFileFilter(new FileNameExtensionFilter("GIF файлы", "GIF"));

        int ret = fileChooser.showDialog(this, "Открыть изображение");

        try {
            if (ret == JFileChooser.APPROVE_OPTION) {
                File pic = new File(fileChooser.getSelectedFile().getAbsolutePath());
                picturePath = "res/pic/" + prodPluTextField.getText() + ".GIF";
                File dest = new File(picturePath);
                java.nio.file.Files.copy(pic.toPath(), dest.toPath(), StandardCopyOption.REPLACE_EXISTING);

                picture = new ImageIcon(ImageIO.read(dest));
                prodPicPanel.getGraphics().drawImage(picture.getImage(), 1, 1, 198, 110, prodPicPanel);
            }
        } catch (IOException e) {
            System.err.println("open image failed... \n" + e.getMessage());
        }
    }//GEN-LAST:event_prodPicPanelMouseClicked

    private void prodDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodDelBtnActionPerformed
        // Del product
        prodMsgLabel.setText("");

        if (prodList.getSelectedIndex() == -1) {
            prodMsgLabel.setText("Выберите продукт!");
        } else {
            regular.removeProduct(prodList.getSelectedIndex());
            prodList.setModel(regular.getProductsAsListModel());

            prodNameTextField.setText("");
            prodPluTextField.setText("");
            picturePath = "";
            prodPicPanel.getGraphics().drawImage(blankPicture.getImage(), 1, 1, 198, 110, prodPicPanel);
            ((ConstructorTableModel) prodTable.getModel()).clearSelection();
            prodTable.updateUI();
        }
    }//GEN-LAST:event_prodDelBtnActionPerformed

    private void termsAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termsAddBtnActionPerformed
        // Add terminal group
        termsMsgLabel.setText("");

        if (termsNameTF.getText().isEmpty()) {
            termsMsgLabel.setText("Введите название группы!");
        } else if (termsAddedList.getModel().getSize() == 0) {
            termsMsgLabel.setText("Добавьте хотя бы одну кассу!");
        } else {
            // add new terminal group and write to file
            java.util.ArrayList<String> terminals = new ArrayList<String>();

            for (int i = 0; i < termsAddedList.getModel().getSize(); i++) {
                terminals.add(termsAddedList.getModel().getElementAt(i));
            }

            regular.addTerminalGroup(termsNameTF.getText(), new ArrayList<String>(terminals));
            termsList.setModel(regular.getTerminalGroupsAsListModel());

            termsNameTF.setText("");
            termsAllList.clearSelection();
            termsAddedList.setModel(new DefaultListModel<String>());
        }
    }//GEN-LAST:event_termsAddBtnActionPerformed

    private void termsDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termsDelBtnActionPerformed
        // Del terminal group
        termsMsgLabel.setText("");

        if (termsList.getSelectedIndex() == -1) {
            termsMsgLabel.setText("Выберите группу!");
        } else {
            regular.removeTreminalGroup(termsList.getSelectedIndex());
            termsList.setModel(regular.getTerminalGroupsAsListModel());

            termsNameTF.setText("");
            termsAllList.clearSelection();
            termsAddedList.setModel(new DefaultListModel<String>());
        }
    }//GEN-LAST:event_termsDelBtnActionPerformed

    private void constrTermGrpComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constrTermGrpComboBoxActionPerformed
        // selection terminal group
        jLabel8.setText(regular.getTerminalGroup(constrTermGrpComboBox.getSelectedIndex()).getTerminalsAsString());
        constrDayOfWeekList.setSelectedIndex(1);
        constrDayOfWeekList.setSelectedIndex(0);
//        constrDaysOfWeekListModel.clear();
//
//        if (constrTermGrpComboBox.getSelectedIndex() != -1) {
//            for (DayOfWeek dow : constructor.getTerminalGroups().get(constrTermGrpComboBox.getSelectedIndex()).getDaysOfWeek()) {
//                constrDaysOfWeekListModel.addElement(dow);
//            }
//        }
    }//GEN-LAST:event_constrTermGrpComboBoxActionPerformed

    private void constrDayOfWeekListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_constrDayOfWeekListValueChanged
        // Day of week changed
        if (!evt.getValueIsAdjusting()) {
            constrConfigurationTree.setModel(constructor.getConstrTreeModel(constrTermGrpComboBox.getSelectedIndex(), constrDayOfWeekList.getSelectedIndex()));

            /*
            1. получить выбранную группу касс 
            2. получить выбранный день недели 
            3. загрузить моделЬ групп для данного дня недели 
            4. открыть модель групп добавленых в день недели 
            5. открыть модель листа всех групп товаров
             */
//            int selectedIndexTerminalGroup = constrTermGrpComboBox.getSelectedIndex();
//            int selectedDayOfWeek = constrDayOfWeekList.getSelectedIndex();
//
//            String[] addedGroup = constructor.getTerminalGroups().get(selectedIndexTerminalGroup).getDaysOfWeek().get(selectedDayOfWeek).getGroupsAsStringArray();
//            constrAllGrp.setModel(constructor.getAllGroupsAsListModel(addedGroup));
//
//            for (int i = 0; i < addedGroup.length; i++) {
//                constrAddedGroupsTable.setValueAt(addedGroup[i], i, 0);
//            }
        }
    }//GEN-LAST:event_constrDayOfWeekListValueChanged

    private void grpListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_grpListValueChanged
        if (!evt.getValueIsAdjusting() && grpList.getSelectedIndex() != -1) {
            grpTF.setText("");
            grpTF1.setText("");

            String[] names = regular.getGroup(grpList.getSelectedIndex()).getName().split("::");
            grpTF.setText(names[0]);
            if (names.length > 1) {
                grpTF1.setText(names[1]);
            }
            //jLabel23.setText(regular.getGroupInfo(grpList.getSelectedIndex()));
        }
    }//GEN-LAST:event_grpListValueChanged

    private void sgrpListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_sgrpListValueChanged
        if (!evt.getValueIsAdjusting() && sgrpList.getSelectedIndex() != -1) {
            sgrpTF.setText("");
            sgrpTF1.setText("");

            String[] names = regular.getSubgroup(sgrpList.getSelectedIndex()).getName().split("::");
            sgrpTF.setText(names[0]);
            if (names.length > 1) {
                sgrpTF1.setText(names[1]);
            }

            sgrpTable.setModel(regular.getGroupsAsTableModel(sgrpList.getSelectedIndex()));
            sgrpTable.getColumnModel().getColumn(0).setMaxWidth(30);
        }
    }//GEN-LAST:event_sgrpListValueChanged

    private void grpListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grpListFocusLost
        grpTF.setText("");
        grpTF1.setText("");
        //grpList.getSelectionModel().clearSelection();
    }//GEN-LAST:event_grpListFocusLost

    private void sgrpListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sgrpListFocusLost
        sgrpTF.setText("");
        sgrpTF1.setText("");
        //sgrpList.getSelectionModel().clearSelection();
        ((ConstructorTableModel) sgrpTable.getModel()).clearSelection();
        sgrpTable.updateUI();
    }//GEN-LAST:event_sgrpListFocusLost

    private void sgrpListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sgrpListFocusGained
        sgrpMsgLabel.setText("");
    }//GEN-LAST:event_sgrpListFocusGained

    private void prodListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_prodListValueChanged
        if (!evt.getValueIsAdjusting() && prodList.getSelectedIndex() != -1) {
            // show name
            prodNameTextField.setText(regular.getProductName(prodList.getSelectedIndex()));
            // show plu
            prodPluTextField.setText(regular.getProductPlu(prodList.getSelectedIndex()));
            //show picture
            try {
                prodPicPanel.getGraphics().drawImage(new ImageIcon(ImageIO.read(new File(regular.getProductPicturePath(prodList.getSelectedIndex())))).getImage(), 1, 1, 198, 110, prodPicPanel);
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
            // show checked subgroups
            prodTable.setModel(regular.getSubgroupsAsTableModel(prodList.getSelectedIndex()));
            prodTable.getColumnModel().getColumn(0).setMaxWidth(30);
        }
    }//GEN-LAST:event_prodListValueChanged

    private void prodListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodListFocusLost
        prodNameTextField.setText("");
        prodPluTextField.setText("");
        //prodList.getSelectionModel().clearSelection();
        picturePath = "";
        prodPicPanel.getGraphics().drawImage(blankPicture.getImage(), 1, 1, 198, 110, prodPicPanel);
        ((ConstructorTableModel) prodTable.getModel()).clearSelection();
        prodTable.updateUI();
    }//GEN-LAST:event_prodListFocusLost

    private void prodListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodListFocusGained
        prodMsgLabel.setText("");
    }//GEN-LAST:event_prodListFocusGained

    private void termsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_termsListValueChanged
        if (!evt.getValueIsAdjusting() && termsList.getSelectedIndex() != -1) {
            // show name
            termsNameTF.setText(regular.getTerminalGroupName(termsList.getSelectedIndex()));
            // show terminals
            termsAddedList.setModel(regular.getTerminalsAsListModel(termsList.getSelectedIndex()));
        }
    }//GEN-LAST:event_termsListValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (termsAllList.getSelectedIndex() == -1) {
            termsMsgLabel.setText("Выберите хотя бы одну кассу!");
        } else {
            DefaultListModel modelA = new DefaultListModel();

            for (int i = 0; i < termsAddedList.getModel().getSize(); i++) {
                modelA.addElement(termsAddedList.getModel().getElementAt(i));
            }

            for (String terminal : termsAllList.getSelectedValuesList()) {

                boolean alreadyExists = false;

                for (int i = 0; i < termsAddedList.getModel().getSize(); i++) {
                    if (terminal.equals(termsAddedList.getModel().getElementAt(i))) {
                        alreadyExists = true;
                        break;
                    }
                }

                if (!alreadyExists) {
                    modelA.addElement(terminal);
                }
            }

            termsAddedList.setModel(modelA);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (termsAddedList.getSelectedIndex() == -1) {
            termsMsgLabel.setText("Выберите хотя бы одну кассу!");
        } else {
            DefaultListModel modelA = new DefaultListModel();

            java.util.List<String> selectedValues = termsAddedList.getSelectedValuesList();

            for (int i = 0; i < termsAddedList.getModel().getSize(); i++) {

                boolean toDelete = false;

                for (String value : selectedValues) {
                    if (value.equals(termsAddedList.getModel().getElementAt(i))) {
                        toDelete = true;
                        break;
                    }
                }

                if (!toDelete) {
                    modelA.addElement(termsAddedList.getModel().getElementAt(i));
                }
            }

            termsAddedList.setModel(modelA);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void termsListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_termsListFocusLost
        termsNameTF.setText("");
        //termsAllList.clearSelection();
        termsAddedList.setModel(new DefaultListModel<String>());
    }//GEN-LAST:event_termsListFocusLost

    private void termsListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_termsListFocusGained
        termsMsgLabel.setText("");
    }//GEN-LAST:event_termsListFocusGained

    private void loadToServerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadToServerItemActionPerformed

        constructor.uploadConfiguration(this);

        // action after export
    }//GEN-LAST:event_loadToServerItemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int level = constrConfigurationTree.getSelectionPath().getPathCount();

        switch (level) {
            case 1: // GroupsConfig

                if (pathForLocation != null) {
                    System.out.println(pathForLocation.getLastPathComponent());

                    constructor.configureDayOfWeek(this, constrTermGrpComboBox.getSelectedIndex(), constrDayOfWeekList.getSelectedIndex());
                    // обновить дерево
                    constrConfigurationTree.setModel(constructor.getConstrTreeModel(constrTermGrpComboBox.getSelectedIndex(), constrDayOfWeekList.getSelectedIndex()));
                }

                break;

            case 2: // SubgroupsConfig

                if (pathForLocation != null) {
                    data.DayOfWeek dow = (data.DayOfWeek) ((DefaultMutableTreeNode) pathForLocation.getParentPath().getLastPathComponent()).getUserObject();
                    //data.Group gr = (data.Group) ((DefaultMutableTreeNode) pathForLocation.getLastPathComponent()).getUserObject();

                    int groupIndex = dow.getGroupNumber(pathForLocation.getLastPathComponent().toString());
//                        
                    constructor.configureGroup(this, constrTermGrpComboBox.getSelectedIndex(), constrDayOfWeekList.getSelectedIndex(), groupIndex);
                    // обновить дерево
                    constrConfigurationTree.setModel(constructor.getConstrTreeModel(constrTermGrpComboBox.getSelectedIndex(), constrDayOfWeekList.getSelectedIndex()));
                }

                break;

            case 3: // ProductsConfig

                if (pathForLocation != null) {
                    System.out.println(pathForLocation.getLastPathComponent());

                    data.DayOfWeek dow = (data.DayOfWeek) ((DefaultMutableTreeNode) pathForLocation.getParentPath().getParentPath().getLastPathComponent()).getUserObject();
                    data.Group gr = (data.Group) ((DefaultMutableTreeNode) pathForLocation.getParentPath().getLastPathComponent()).getUserObject();
                    data.Subgroup sg = (data.Subgroup) ((DefaultMutableTreeNode) pathForLocation.getLastPathComponent()).getUserObject();

                    int groupIndex = dow.getGroupNumber(gr.toString());
                    int subgroupIndex = gr.getSubgroupNumber(sg.toString());

                    constructor.configureSubgroup(this, constrTermGrpComboBox.getSelectedIndex(), constrDayOfWeekList.getSelectedIndex(), groupIndex, subgroupIndex);
                    // обновить дерево
                    constrConfigurationTree.setModel(constructor.getConstrTreeModel(constrTermGrpComboBox.getSelectedIndex(), constrDayOfWeekList.getSelectedIndex()));
                }
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void constrConfigurationTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_constrConfigurationTreeValueChanged

        if (constrConfigurationTree.getSelectionPath() != null) {
            int level = constrConfigurationTree.getSelectionPath().getPathCount();
            pathForLocation = evt.getPath();

            SimpleAttributeSet normal = new SimpleAttributeSet();
            StyleConstants.setForeground(normal, Color.black);

            SimpleAttributeSet allert = new SimpleAttributeSet();
            StyleConstants.setForeground(allert, Color.red);

            SimpleAttributeSet good = new SimpleAttributeSet();
            StyleConstants.setForeground(good, Color.GREEN);

            StyledDocument doc = ((StyledDocument) jTextPane1.getDocument());
            String valid, out;

            // clear UI
            jTextPane1.setText("");
            try {
                ImageIcon picture = new ImageIcon(ImageIO.read(getClass().getResource("/resources/blank.png")));
                constrMonitor.getGraphics().drawImage(picture.getImage(), 1, 1, 370, 256, constrMonitor);
            } catch (IOException e) {
                System.err.println(e.getMessage());
            }

            try {
                switch (level) {

                    case 1: // dayOfWeek
                        data.DayOfWeek dayOfWeek = (data.DayOfWeek) ((DefaultMutableTreeNode) pathForLocation.getLastPathComponent()).getUserObject();
                        //System.out.println(dayOfWeek.getGroupNumber(pathForLocation.getLastPathComponent().toString()));

                        out = "День недели: " + dayOfWeek.toString() + "\n"
                                + "Последнее изменение: " + dayOfWeek.getModifiedDate() + "\n";

                        doc.insertString(doc.getLength(), out, normal);
                        break;

                    case 2: // group
                        data.DayOfWeek dow = (data.DayOfWeek) ((DefaultMutableTreeNode) pathForLocation.getParentPath().getLastPathComponent()).getUserObject();
                        data.Group group = (data.Group) ((DefaultMutableTreeNode) pathForLocation.getLastPathComponent()).getUserObject();

                        out = "Товарная группа: " + group.toString() + "\n"
                                + "Номер позиции: " + (dow.getGroupNumber(pathForLocation.getLastPathComponent().toString()) + 1) + "\n"
                                + "Время создания: " + group.getCreationDate() + "\n"
                                + "Последнее изменение: " + group.getModifiedDate() + "\n";

                        doc.insertString(doc.getLength(), out, normal);

                        if (group.isValid()) {
                            valid = "[данная группа отсутствует в справочнике]";
                            doc.insertString(doc.getLength(), valid, allert);
                        } else {
                            valid = "[товарная группа актуальна]";
                            doc.insertString(doc.getLength(), valid, good);
                        }
                        break;

                    case 3: // subgroup
                        data.Group g = (data.Group) ((DefaultMutableTreeNode) pathForLocation.getParentPath().getLastPathComponent()).getUserObject();
                        data.Subgroup subgroup = (data.Subgroup) ((DefaultMutableTreeNode) pathForLocation.getLastPathComponent()).getUserObject();

                        out = "Товарная подгруппа: " + subgroup.toString() + "\n"
                                + "Номер позиции: " + (g.getSubgroupNumber(pathForLocation.getLastPathComponent().toString()) + 1) + "\n"
                                + "Время создания: " + subgroup.getCreationDate() + "\n"
                                + "Последнее изменение: " + subgroup.getModifiedDate() + "\n";

                        doc.insertString(doc.getLength(), out, normal);

                        if (subgroup.isValid()) {
                            valid = "[данная подгруппа отсутствует в справочнике]";
                            doc.insertString(doc.getLength(), valid, allert);
                        } else {
                            valid = "[товарная подгруппа актуальна]";
                            doc.insertString(doc.getLength(), valid, good);
                        }

                        String path = subgroup.getPicturePath();
                        if (path != null) {
                            System.out.println(path);
                            try {
                                ImageIcon picture = new ImageIcon(ImageIO.read(new File(path)));
                                constrMonitor.getGraphics().drawImage(picture.getImage(), 1, 1, 370, 256, constrMonitor);

                            } catch (IOException e) {
                                System.err.println(e.getMessage());
                            }
                        }

                        break;

                    case 4: // product
                        data.Subgroup sg = (data.Subgroup) ((DefaultMutableTreeNode) pathForLocation.getParentPath().getLastPathComponent()).getUserObject();
                        data.Product product = (data.Product) ((DefaultMutableTreeNode) pathForLocation.getLastPathComponent()).getUserObject();

                        out = "Товарная позиция: " + product.toString() + "\n"
                                + "Номер позиции: " + (sg.getProductNumber(pathForLocation.getLastPathComponent().toString()) + 1) + "\n"
                                + "PLU: " + product.getPlu() + "\n"
                                + "Время создания: " + product.getCreationDate() + "\n";

                        doc.insertString(doc.getLength(), out, normal);

                        if (product.isValid()) {
                            valid = "[данный товар отсутствует в справочнике]";
                            doc.insertString(doc.getLength(), valid, allert);
                        } else {
                            valid = "[данный товар актуален]";
                            doc.insertString(doc.getLength(), valid, good);
                        }

                        try {
                            ImageIcon picture = new ImageIcon(ImageIO.read(new File(product.getPicturePath())));
                            constrMonitor.getGraphics().drawImage(picture.getImage(), 1, 1, 198, 110, constrMonitor);
                        } catch (IOException e) {
                            System.err.println(e.getMessage());
                        }

                        break;
                }
            } catch (BadLocationException e) {

            }
        }
    }//GEN-LAST:event_constrConfigurationTreeValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree constrConfigurationTree;
    private javax.swing.JList<String> constrDayOfWeekList;
    private javax.swing.JPanel constrMonitor;
    private javax.swing.JComboBox<String> constrTermGrpComboBox;
    private javax.swing.JPanel constructorPanel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel groupPanel;
    private javax.swing.JButton grpAddBtn;
    private javax.swing.JButton grpDelBtn;
    private javax.swing.JList<String> grpList;
    private javax.swing.JLabel grpMessageLabel;
    private javax.swing.JTextField grpTF;
    private javax.swing.JTextField grpTF1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuItem loadToServerItem;
    private javax.swing.JButton prodAddBtn;
    private javax.swing.JButton prodDelBtn;
    private javax.swing.JList<String> prodList;
    private javax.swing.JLabel prodMsgLabel;
    private javax.swing.JTextField prodNameTextField;
    private javax.swing.JPanel prodPicPanel;
    private javax.swing.JTextField prodPluTextField;
    private javax.swing.JTable prodTable;
    private javax.swing.JPanel productPanel;
    private javax.swing.JButton sgrpAddBtn;
    private javax.swing.JButton sgrpDelBtn;
    private javax.swing.JList<String> sgrpList;
    private javax.swing.JLabel sgrpMsgLabel;
    private javax.swing.JTextField sgrpTF;
    private javax.swing.JTextField sgrpTF1;
    private javax.swing.JTable sgrpTable;
    private javax.swing.JPanel subgroupPanel;
    private javax.swing.JButton termsAddBtn;
    private javax.swing.JList<String> termsAddedList;
    private javax.swing.JList<String> termsAllList;
    private javax.swing.JButton termsDelBtn;
    private javax.swing.JList<String> termsList;
    private javax.swing.JLabel termsMsgLabel;
    private javax.swing.JTextField termsNameTF;
    private javax.swing.JPanel termsPanel;
    // End of variables declaration//GEN-END:variables
}
