package gui;

import data.Button;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ivan
 */
public class Edit extends javax.swing.JDialog {

    private java.awt.Frame parent;

    private final Button[] buttons;
    private int selectedField;
    private ImageIcon image;

    /**
     * Creates new form Edit
     *
     * @param parent
     * @param modal
     * @param buttons
     */
    public Edit(java.awt.Frame parent, boolean modal, Button[] buttons) {
        super(parent, modal);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        this.parent = parent;
        this.buttons = buttons;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textFieldPlu1 = new javax.swing.JTextField();
        textFieldPlu2 = new javax.swing.JTextField();
        textFieldPlu3 = new javax.swing.JTextField();
        textFieldPlu4 = new javax.swing.JTextField();
        textFieldPlu5 = new javax.swing.JTextField();
        textFieldPlu6 = new javax.swing.JTextField();
        textFieldPlu7 = new javax.swing.JTextField();
        textFieldPlu8 = new javax.swing.JTextField();
        textFieldPlu9 = new javax.swing.JTextField();
        textFieldPlu10 = new javax.swing.JTextField();
        textFieldPlu11 = new javax.swing.JTextField();
        textFieldPlu12 = new javax.swing.JTextField();
        textFieldPlu13 = new javax.swing.JTextField();
        textFieldPlu14 = new javax.swing.JTextField();
        textFieldPlu15 = new javax.swing.JTextField();
        textFieldPlu16 = new javax.swing.JTextField();
        textFieldPlu17 = new javax.swing.JTextField();
        textFieldPlu18 = new javax.swing.JTextField();
        textFieldPlu19 = new javax.swing.JTextField();
        textFieldPlu20 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nameRecord1 = new javax.swing.JTextField();
        nameRecord2 = new javax.swing.JTextField();
        nameRecord3 = new javax.swing.JTextField();
        nameRecord4 = new javax.swing.JTextField();
        nameRecord5 = new javax.swing.JTextField();
        nameRecord6 = new javax.swing.JTextField();
        nameRecord7 = new javax.swing.JTextField();
        nameRecord8 = new javax.swing.JTextField();
        nameRecord9 = new javax.swing.JTextField();
        nameRecord10 = new javax.swing.JTextField();
        nameRecord11 = new javax.swing.JTextField();
        nameRecord12 = new javax.swing.JTextField();
        nameRecord13 = new javax.swing.JTextField();
        nameRecord14 = new javax.swing.JTextField();
        nameRecord15 = new javax.swing.JTextField();
        nameRecord16 = new javax.swing.JTextField();
        nameRecord17 = new javax.swing.JTextField();
        nameRecord18 = new javax.swing.JTextField();
        nameRecord19 = new javax.swing.JTextField();
        nameRecord20 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        chooseImageButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Изменение раскладки");
        setModal(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 630));
        jPanel1.setName(""); // NOI18N

        textFieldPlu1.setDocument(new LimitedDocument(11, new MyDocumentFilter())
        );
        textFieldPlu1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu1.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu1.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu1FocusGained(evt);
            }
        });

        textFieldPlu2.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu2.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu2.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu2FocusGained(evt);
            }
        });

        textFieldPlu3.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu3.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu3.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu3FocusGained(evt);
            }
        });

        textFieldPlu4.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu4.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu4.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu4FocusGained(evt);
            }
        });

        textFieldPlu5.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu5.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu5.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu5FocusGained(evt);
            }
        });

        textFieldPlu6.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu6.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu6.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu6FocusGained(evt);
            }
        });

        textFieldPlu7.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu7.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu7.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu7FocusGained(evt);
            }
        });

        textFieldPlu8.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu8.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu8.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu8FocusGained(evt);
            }
        });

        textFieldPlu9.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu9.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu9.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu9FocusGained(evt);
            }
        });

        textFieldPlu10.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu10.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu10.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu10FocusGained(evt);
            }
        });

        textFieldPlu11.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu11.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu11.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu11FocusGained(evt);
            }
        });

        textFieldPlu12.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu12.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu12.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu12FocusGained(evt);
            }
        });

        textFieldPlu13.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu13.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu13.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu13FocusGained(evt);
            }
        });

        textFieldPlu14.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu14.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu14.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu14FocusGained(evt);
            }
        });

        textFieldPlu15.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu15.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu15.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu15FocusGained(evt);
            }
        });

        textFieldPlu16.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu16.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu16.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu16FocusGained(evt);
            }
        });

        textFieldPlu17.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu17.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu17.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu17FocusGained(evt);
            }
        });

        textFieldPlu18.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu18.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu18.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu18.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu18FocusGained(evt);
            }
        });

        textFieldPlu19.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu19.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu19.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu19FocusGained(evt);
            }
        });

        textFieldPlu20.setDocument(new LimitedDocument(11, new MyDocumentFilter()));
        textFieldPlu20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldPlu20.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        textFieldPlu20.setMinimumSize(new java.awt.Dimension(80, 24));
        textFieldPlu20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPlu20FocusGained(evt);
            }
        });

        jLabel1.setText("Кнопка 01:");
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel2.setText("Кнопка 02:");
        jLabel2.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel2.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel3.setText("Кнопка 03:");
        jLabel3.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel3.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel4.setText("Кнопка 04:");
        jLabel4.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel4.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel5.setText("Кнопка 05:");
        jLabel5.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel5.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel6.setText("Кнопка 06:");
        jLabel6.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel6.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel6.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel7.setText("Кнопка 07:");
        jLabel7.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel7.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel8.setText("Кнопка 08:");
        jLabel8.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel8.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel9.setText("Кнопка 09:");
        jLabel9.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel9.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel10.setText("Кнопка 10:");
        jLabel10.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel10.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel11.setText("Кнопка 11:");
        jLabel11.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel11.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel11.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel12.setText("Кнопка 12:");
        jLabel12.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel12.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel12.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel13.setText("Кнопка 13:");
        jLabel13.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel13.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel13.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel14.setText("Кнопка 14:");
        jLabel14.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel14.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel14.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel15.setText("Кнопка 15:");
        jLabel15.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel15.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel15.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel16.setText("Кнопка 16:");
        jLabel16.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel16.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel16.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel17.setText("Кнопка 17:");
        jLabel17.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel17.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel17.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel18.setText("Кнопка 18:");
        jLabel18.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel18.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel18.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel19.setText("Кнопка 19:");
        jLabel19.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel19.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel19.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel20.setText("Кнопка 20:");
        jLabel20.setToolTipText("");
        jLabel20.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        jLabel20.setMinimumSize(new java.awt.Dimension(55, 20));
        jLabel20.setPreferredSize(new java.awt.Dimension(55, 20));

        jLabel21.setText("PLU");

        jLabel22.setText("НАИМЕНОВАНИЕ ТОВАРА");

        nameRecord1.setDocument(new LimitedDocument(30));
        nameRecord1.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord1.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord1.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord1FocusGained(evt);
            }
        });

        nameRecord2.setDocument(new LimitedDocument(30));
        nameRecord2.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord2.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord2.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord2FocusGained(evt);
            }
        });

        nameRecord3.setDocument(new LimitedDocument(30));
        nameRecord3.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord3.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord3.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord3FocusGained(evt);
            }
        });

        nameRecord4.setDocument(new LimitedDocument(30));
        nameRecord4.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord4.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord4.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord4FocusGained(evt);
            }
        });

        nameRecord5.setDocument(new LimitedDocument(30));
        nameRecord5.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord5.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord5.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord5FocusGained(evt);
            }
        });

        nameRecord6.setDocument(new LimitedDocument(30));
        nameRecord6.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord6.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord6.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord6FocusGained(evt);
            }
        });

        nameRecord7.setDocument(new LimitedDocument(30));
        nameRecord7.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord7.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord7.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord7FocusGained(evt);
            }
        });

        nameRecord8.setDocument(new LimitedDocument(30));
        nameRecord8.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord8.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord8.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord8FocusGained(evt);
            }
        });

        nameRecord9.setDocument(new LimitedDocument(30));
        nameRecord9.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord9.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord9.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord9FocusGained(evt);
            }
        });

        nameRecord10.setDocument(new LimitedDocument(30));
        nameRecord10.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord10.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord10.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord10FocusGained(evt);
            }
        });

        nameRecord11.setDocument(new LimitedDocument(30));
        nameRecord11.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord11.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord11.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord11FocusGained(evt);
            }
        });

        nameRecord12.setDocument(new LimitedDocument(30));
        nameRecord12.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord12.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord12.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord12FocusGained(evt);
            }
        });

        nameRecord13.setDocument(new LimitedDocument(30));
        nameRecord13.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord13.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord13.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord13FocusGained(evt);
            }
        });

        nameRecord14.setDocument(new LimitedDocument(30));
        nameRecord14.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord14.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord14.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord14FocusGained(evt);
            }
        });

        nameRecord15.setDocument(new LimitedDocument(30));
        nameRecord15.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord15.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord15.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord15FocusGained(evt);
            }
        });

        nameRecord16.setDocument(new LimitedDocument(30));
        nameRecord16.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord16.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord16.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord16FocusGained(evt);
            }
        });

        nameRecord17.setDocument(new LimitedDocument(30));
        nameRecord17.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord17.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord17.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord17FocusGained(evt);
            }
        });

        nameRecord18.setDocument(new LimitedDocument(30));
        nameRecord18.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord18.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord18.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord18FocusGained(evt);
            }
        });

        nameRecord19.setDocument(new LimitedDocument(30));
        nameRecord19.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord19.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord19.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord19FocusGained(evt);
            }
        });

        nameRecord20.setDocument(new LimitedDocument(30));
        nameRecord20.setMaximumSize(new java.awt.Dimension(2147483647, 24));
        nameRecord20.setMinimumSize(new java.awt.Dimension(200, 24));
        nameRecord20.setPreferredSize(new java.awt.Dimension(200, 20));
        nameRecord20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameRecord20FocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel2, jLabel20, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameRecord5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameRecord7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameRecord9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameRecord11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameRecord13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameRecord15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameRecord17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameRecord19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPlu19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldPlu20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRecord20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel2, jLabel20, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, nameRecord1, nameRecord10, nameRecord11, nameRecord12, nameRecord13, nameRecord14, nameRecord15, nameRecord16, nameRecord17, nameRecord18, nameRecord19, nameRecord2, nameRecord20, nameRecord3, nameRecord4, nameRecord5, nameRecord6, nameRecord7, nameRecord8, nameRecord9, textFieldPlu1, textFieldPlu10, textFieldPlu11, textFieldPlu12, textFieldPlu13, textFieldPlu14, textFieldPlu15, textFieldPlu16, textFieldPlu17, textFieldPlu18, textFieldPlu19, textFieldPlu2, textFieldPlu20, textFieldPlu3, textFieldPlu4, textFieldPlu5, textFieldPlu6, textFieldPlu7, textFieldPlu8, textFieldPlu9});

        textFieldPlu1.setText(buttons[0].getPlu());
        textFieldPlu2.setText(buttons[1].getPlu());
        textFieldPlu3.setText(buttons[2].getPlu());
        textFieldPlu4.setText(buttons[3].getPlu());
        textFieldPlu5.setText(buttons[4].getPlu());
        textFieldPlu6.setText(buttons[5].getPlu());
        textFieldPlu7.setText(buttons[6].getPlu());
        textFieldPlu8.setText(buttons[7].getPlu());
        textFieldPlu9.setText(buttons[8].getPlu());
        textFieldPlu10.setText(buttons[9].getPlu());
        textFieldPlu11.setText(buttons[10].getPlu());
        textFieldPlu12.setText(buttons[11].getPlu());
        textFieldPlu13.setText(buttons[12].getPlu());
        textFieldPlu14.setText(buttons[13].getPlu());
        textFieldPlu15.setText(buttons[14].getPlu());
        textFieldPlu16.setText(buttons[15].getPlu());
        textFieldPlu17.setText(buttons[16].getPlu());
        textFieldPlu18.setText(buttons[17].getPlu());
        textFieldPlu19.setText(buttons[18].getPlu());
        textFieldPlu20.setText(buttons[19].getPlu());
        nameRecord1.setText(buttons[0].getText());
        nameRecord2.setText(buttons[1].getText());
        nameRecord3.setText(buttons[2].getText());
        nameRecord4.setText(buttons[3].getText());
        nameRecord5.setText(buttons[4].getText());
        nameRecord6.setText(buttons[5].getText());
        nameRecord7.setText(buttons[6].getText());
        nameRecord8.setText(buttons[7].getText());
        nameRecord9.setText(buttons[8].getText());
        nameRecord10.setText(buttons[9].getText());
        nameRecord11.setText(buttons[10].getText());
        nameRecord12.setText(buttons[11].getText());
        nameRecord13.setText(buttons[12].getText());
        nameRecord14.setText(buttons[13].getText());
        nameRecord15.setText(buttons[14].getText());
        nameRecord16.setText(buttons[15].getText());
        nameRecord17.setText(buttons[16].getText());
        nameRecord18.setText(buttons[17].getText());
        nameRecord19.setText(buttons[18].getText());
        nameRecord20.setText(buttons[19].getText());

        imagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagePanel.setPreferredSize(new java.awt.Dimension(111, 63));

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        chooseImageButton.setText("Выбрать");
        chooseImageButton.setEnabled(false);
        chooseImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImageButtonActionPerformed(evt);
            }
        });

        jLabel23.setText("ИЗОБРАЖЕНИЕ");

        okButton.setText("OK");
        okButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                okButtonFocusGained(evt);
            }
        });
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Отмена");
        cancelButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cancelButtonFocusGained(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Удалить");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel23)
                    .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseImageButton)
                    .addComponent(okButton)
                    .addComponent(cancelButton)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, chooseImageButton, deleteButton, okButton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseImageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelButton, chooseImageButton, deleteButton, okButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String formatText(String text) {

        String outputString = "";

        text = text.trim();

        if (!text.isEmpty()) {
            outputString += String.valueOf(text.charAt(0)).toUpperCase();

            if (text.length() > 1) {
                outputString += text.substring(1, text.length()).toLowerCase();
            }
        }

        return outputString;
    }

    private String formatPluText(String text) {

        String outputString = "";

        if (!text.trim().equals("")) {
            for (int i = 0; i < text.length();) {
                outputString += text.charAt(i);
                outputString += text.charAt(i + 1);
                outputString += " ";
            }

        }

        return outputString;
    }

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        buttons[0].setPlu(textFieldPlu1.getText());
        buttons[0].setText(formatText(nameRecord1.getText()));

        buttons[1].setPlu(textFieldPlu2.getText());
        buttons[1].setText(formatText(nameRecord2.getText()));

        buttons[2].setPlu(textFieldPlu3.getText());
        buttons[2].setText(formatText(nameRecord3.getText()));

        buttons[3].setPlu(textFieldPlu4.getText());
        buttons[3].setText(formatText(nameRecord4.getText()));

        buttons[4].setPlu(textFieldPlu5.getText());
        buttons[4].setText(formatText(nameRecord5.getText()));

        buttons[5].setPlu(textFieldPlu6.getText());
        buttons[5].setText(formatText(nameRecord6.getText()));

        buttons[6].setPlu(textFieldPlu7.getText());
        buttons[6].setText(formatText(nameRecord7.getText()));

        buttons[7].setPlu(textFieldPlu8.getText());
        buttons[7].setText(formatText(nameRecord8.getText()));

        buttons[8].setPlu(textFieldPlu9.getText());
        buttons[8].setText(formatText(nameRecord9.getText()));

        buttons[9].setPlu(textFieldPlu10.getText());
        buttons[9].setText(formatText(nameRecord10.getText()));

        buttons[10].setPlu(textFieldPlu11.getText());
        buttons[10].setText(formatText(nameRecord11.getText()));

        buttons[11].setPlu(textFieldPlu12.getText());
        buttons[11].setText(formatText(nameRecord12.getText()));

        buttons[12].setPlu(textFieldPlu13.getText());
        buttons[12].setText(formatText(nameRecord13.getText()));

        buttons[13].setPlu(textFieldPlu14.getText());
        buttons[13].setText(formatText(nameRecord14.getText()));

        buttons[14].setPlu(textFieldPlu15.getText());
        buttons[14].setText(formatText(nameRecord15.getText()));

        buttons[15].setPlu(textFieldPlu16.getText());
        buttons[15].setText(formatText(nameRecord16.getText()));

        buttons[16].setPlu(textFieldPlu17.getText());
        buttons[16].setText(formatText(nameRecord17.getText()));

        buttons[17].setPlu(textFieldPlu18.getText());
        buttons[17].setText(formatText(nameRecord18.getText()));

        buttons[18].setPlu(textFieldPlu19.getText());
        buttons[18].setText(formatText(nameRecord19.getText()));

        buttons[19].setPlu(textFieldPlu20.getText());
        buttons[19].setText(formatText(nameRecord20.getText()));

        ((TouchBuilder) parent).isModified = true;
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void chooseImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImageButtonActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("./"));
        fileChooser.setFileFilter(new FileNameExtensionFilter("GIF файлы", "GIF"));

        int ret = fileChooser.showDialog(this, "Открыть изображение");

        try {
            if (ret == JFileChooser.APPROVE_OPTION) {
                image = new ImageIcon(ImageIO.read(new File(fileChooser.getSelectedFile().getAbsolutePath())));

                if (image.getIconWidth() != 109 || image.getIconHeight() != 61) {
                    JOptionPane jop = new JOptionPane("Выбранное изображение имеет несовместимый размер!\n"
                            + "Выберите изображение размером: 109 x 61", JOptionPane.OK_OPTION);
                    JDialog dialog = jop.createDialog(this, "Несовместимый формат");
                    dialog.show();
                } else {

                    imagePanel.getGraphics().drawImage(image.getImage(), 1, 1, imagePanel);

                    switch (selectedField) {
                        case 0:
                            buttons[0].setImage(image);
                            break;

                        case 1:
                            buttons[1].setImage(image);
                            break;

                        case 2:
                            buttons[2].setImage(image);
                            break;

                        case 3:
                            buttons[3].setImage(image);
                            break;

                        case 4:
                            buttons[4].setImage(image);
                            break;

                        case 5:
                            buttons[5].setImage(image);
                            break;

                        case 6:
                            buttons[6].setImage(image);
                            break;

                        case 7:
                            buttons[7].setImage(image);
                            break;

                        case 8:
                            buttons[8].setImage(image);
                            break;

                        case 9:
                            buttons[9].setImage(image);
                            break;

                        case 10:
                            buttons[10].setImage(image);
                            break;

                        case 11:
                            buttons[11].setImage(image);
                            break;

                        case 12:
                            buttons[12].setImage(image);
                            break;

                        case 13:
                            buttons[13].setImage(image);
                            break;

                        case 14:
                            buttons[14].setImage(image);
                            break;

                        case 15:
                            buttons[15].setImage(image);
                            break;

                        case 16:
                            buttons[16].setImage(image);
                            break;

                        case 17:
                            buttons[17].setImage(image);
                            break;

                        case 18:
                            buttons[18].setImage(image);
                            break;

                        case 19:
                            buttons[19].setImage(image);
                            break;
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("open image failed... " + e.getMessage());
        }
    }//GEN-LAST:event_chooseImageButtonActionPerformed

    private void nameRecord1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord1FocusGained
        selectedField = 0;
        imagePanel.getGraphics().drawImage(buttons[0].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord1FocusGained

    private void nameRecord2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord2FocusGained
        selectedField = 1;
        imagePanel.getGraphics().drawImage(buttons[1].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord2FocusGained

    private void nameRecord3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord3FocusGained
        selectedField = 2;
        imagePanel.getGraphics().drawImage(buttons[2].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord3FocusGained

    private void nameRecord4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord4FocusGained
        selectedField = 3;
        imagePanel.getGraphics().drawImage(buttons[3].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord4FocusGained

    private void nameRecord5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord5FocusGained
        selectedField = 4;
        imagePanel.getGraphics().drawImage(buttons[4].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord5FocusGained

    private void nameRecord6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord6FocusGained
        selectedField = 5;
        imagePanel.getGraphics().drawImage(buttons[5].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord6FocusGained

    private void nameRecord7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord7FocusGained
        selectedField = 6;
        imagePanel.getGraphics().drawImage(buttons[6].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord7FocusGained

    private void nameRecord8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord8FocusGained
        selectedField = 7;
        imagePanel.getGraphics().drawImage(buttons[7].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord8FocusGained

    private void nameRecord9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord9FocusGained
        selectedField = 8;
        imagePanel.getGraphics().drawImage(buttons[8].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord9FocusGained

    private void nameRecord10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord10FocusGained
        selectedField = 9;
        imagePanel.getGraphics().drawImage(buttons[9].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord10FocusGained

    private void nameRecord12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord12FocusGained
        selectedField = 11;
        imagePanel.getGraphics().drawImage(buttons[11].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord12FocusGained

    private void nameRecord13FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord13FocusGained
        selectedField = 12;
        imagePanel.getGraphics().drawImage(buttons[12].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord13FocusGained

    private void nameRecord14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord14FocusGained
        selectedField = 13;
        imagePanel.getGraphics().drawImage(buttons[13].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord14FocusGained

    private void nameRecord15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord15FocusGained
        selectedField = 14;
        imagePanel.getGraphics().drawImage(buttons[14].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord15FocusGained

    private void nameRecord16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord16FocusGained
        selectedField = 15;
        imagePanel.getGraphics().drawImage(buttons[15].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord16FocusGained

    private void nameRecord17FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord17FocusGained
        selectedField = 16;
        imagePanel.getGraphics().drawImage(buttons[16].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord17FocusGained

    private void nameRecord18FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord18FocusGained
        selectedField = 17;
        imagePanel.getGraphics().drawImage(buttons[17].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord18FocusGained

    private void nameRecord19FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord19FocusGained
        selectedField = 18;
        imagePanel.getGraphics().drawImage(buttons[18].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord19FocusGained

    private void nameRecord20FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord20FocusGained
        selectedField = 19;
        imagePanel.getGraphics().drawImage(buttons[19].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord20FocusGained

    private void nameRecord11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameRecord11FocusGained
        selectedField = 10;
        imagePanel.getGraphics().drawImage(buttons[10].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_nameRecord11FocusGained

    private void textFieldPlu1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu1FocusGained
        selectedField = 0;
        imagePanel.getGraphics().drawImage(buttons[0].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu1FocusGained

    private void textFieldPlu2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu2FocusGained
        selectedField = 1;
        imagePanel.getGraphics().drawImage(buttons[1].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu2FocusGained

    private void textFieldPlu3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu3FocusGained
        selectedField = 2;
        imagePanel.getGraphics().drawImage(buttons[2].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu3FocusGained

    private void textFieldPlu4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu4FocusGained
        selectedField = 3;
        imagePanel.getGraphics().drawImage(buttons[3].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu4FocusGained

    private void textFieldPlu5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu5FocusGained
        selectedField = 4;
        imagePanel.getGraphics().drawImage(buttons[4].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu5FocusGained

    private void textFieldPlu6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu6FocusGained
        selectedField = 5;
        imagePanel.getGraphics().drawImage(buttons[5].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu6FocusGained

    private void textFieldPlu7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu7FocusGained
        selectedField = 6;
        imagePanel.getGraphics().drawImage(buttons[6].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu7FocusGained

    private void textFieldPlu8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu8FocusGained
        selectedField = 7;
        imagePanel.getGraphics().drawImage(buttons[7].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu8FocusGained

    private void textFieldPlu9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu9FocusGained
        selectedField = 8;
        imagePanel.getGraphics().drawImage(buttons[8].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu9FocusGained

    private void textFieldPlu10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu10FocusGained
        selectedField = 9;
        imagePanel.getGraphics().drawImage(buttons[9].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu10FocusGained

    private void textFieldPlu11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu11FocusGained
        selectedField = 10;
        imagePanel.getGraphics().drawImage(buttons[10].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu11FocusGained

    private void textFieldPlu12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu12FocusGained
        selectedField = 11;
        imagePanel.getGraphics().drawImage(buttons[11].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu12FocusGained

    private void textFieldPlu13FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu13FocusGained
        selectedField = 12;
        imagePanel.getGraphics().drawImage(buttons[12].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu13FocusGained

    private void textFieldPlu14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu14FocusGained
        selectedField = 13;
        imagePanel.getGraphics().drawImage(buttons[13].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu14FocusGained

    private void textFieldPlu15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu15FocusGained
        selectedField = 14;
        imagePanel.getGraphics().drawImage(buttons[14].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu15FocusGained

    private void textFieldPlu16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu16FocusGained
        selectedField = 15;
        imagePanel.getGraphics().drawImage(buttons[15].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu16FocusGained

    private void textFieldPlu17FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu17FocusGained
        selectedField = 16;
        imagePanel.getGraphics().drawImage(buttons[16].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu17FocusGained

    private void textFieldPlu18FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu18FocusGained
        selectedField = 17;
        imagePanel.getGraphics().drawImage(buttons[17].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu18FocusGained

    private void textFieldPlu19FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu19FocusGained
        selectedField = 18;
        imagePanel.getGraphics().drawImage(buttons[18].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu19FocusGained

    private void textFieldPlu20FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPlu20FocusGained
        selectedField = 19;
        imagePanel.getGraphics().drawImage(buttons[19].getImage().getImage(), 1, 1, imagePanel);
        chooseImageButton.setEnabled(true);
    }//GEN-LAST:event_textFieldPlu20FocusGained

    private void okButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_okButtonFocusGained
        chooseImageButton.setEnabled(false);
    }//GEN-LAST:event_okButtonFocusGained

    private void cancelButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cancelButtonFocusGained
        chooseImageButton.setEnabled(false);
    }//GEN-LAST:event_cancelButtonFocusGained

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        try {
            ImageIcon emptyImage = new ImageIcon(ImageIO.read(getClass().getResource("/resources/empty.gif")));
            imagePanel.getGraphics().drawImage(emptyImage.getImage(), 1, 1, imagePanel);

            switch (selectedField) {
                case 0:
                    buttons[0].setImage(emptyImage);
                    break;

                case 1:
                    buttons[1].setImage(emptyImage);
                    break;

                case 2:
                    buttons[2].setImage(emptyImage);
                    break;

                case 3:
                    buttons[3].setImage(emptyImage);
                    break;

                case 4:
                    buttons[4].setImage(emptyImage);
                    break;

                case 5:
                    buttons[5].setImage(emptyImage);
                    break;

                case 6:
                    buttons[6].setImage(emptyImage);
                    break;

                case 7:
                    buttons[7].setImage(emptyImage);
                    break;

                case 8:
                    buttons[8].setImage(emptyImage);
                    break;

                case 9:
                    buttons[9].setImage(emptyImage);
                    break;

                case 10:
                    buttons[10].setImage(emptyImage);
                    break;

                case 11:
                    buttons[11].setImage(emptyImage);
                    break;

                case 12:
                    buttons[12].setImage(emptyImage);
                    break;

                case 13:
                    buttons[13].setImage(emptyImage);
                    break;

                case 14:
                    buttons[14].setImage(emptyImage);
                    break;

                case 15:
                    buttons[15].setImage(emptyImage);
                    break;

                case 16:
                    buttons[16].setImage(emptyImage);
                    break;

                case 17:
                    buttons[17].setImage(emptyImage);
                    break;

                case 18:
                    buttons[18].setImage(emptyImage);
                    break;

                case 19:
                    buttons[19].setImage(emptyImage);
                    break;
            }
        } catch (IOException e) {
            System.out.println("IO error empty.gif read... " + e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton chooseImageButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameRecord1;
    private javax.swing.JTextField nameRecord10;
    private javax.swing.JTextField nameRecord11;
    private javax.swing.JTextField nameRecord12;
    private javax.swing.JTextField nameRecord13;
    private javax.swing.JTextField nameRecord14;
    private javax.swing.JTextField nameRecord15;
    private javax.swing.JTextField nameRecord16;
    private javax.swing.JTextField nameRecord17;
    private javax.swing.JTextField nameRecord18;
    private javax.swing.JTextField nameRecord19;
    private javax.swing.JTextField nameRecord2;
    private javax.swing.JTextField nameRecord20;
    private javax.swing.JTextField nameRecord3;
    private javax.swing.JTextField nameRecord4;
    private javax.swing.JTextField nameRecord5;
    private javax.swing.JTextField nameRecord6;
    private javax.swing.JTextField nameRecord7;
    private javax.swing.JTextField nameRecord8;
    private javax.swing.JTextField nameRecord9;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField textFieldPlu1;
    private javax.swing.JTextField textFieldPlu10;
    private javax.swing.JTextField textFieldPlu11;
    private javax.swing.JTextField textFieldPlu12;
    private javax.swing.JTextField textFieldPlu13;
    private javax.swing.JTextField textFieldPlu14;
    private javax.swing.JTextField textFieldPlu15;
    private javax.swing.JTextField textFieldPlu16;
    private javax.swing.JTextField textFieldPlu17;
    private javax.swing.JTextField textFieldPlu18;
    private javax.swing.JTextField textFieldPlu19;
    private javax.swing.JTextField textFieldPlu2;
    private javax.swing.JTextField textFieldPlu20;
    private javax.swing.JTextField textFieldPlu3;
    private javax.swing.JTextField textFieldPlu4;
    private javax.swing.JTextField textFieldPlu5;
    private javax.swing.JTextField textFieldPlu6;
    private javax.swing.JTextField textFieldPlu7;
    private javax.swing.JTextField textFieldPlu8;
    private javax.swing.JTextField textFieldPlu9;
    // End of variables declaration//GEN-END:variables

}
