/*
 * Copyright (C) 2017 Ivan Naumov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gui;

import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

/**
 *
 * @author ivan
 */
public class AddingTerminals extends javax.swing.JDialog {

    private static AddingTerminals instance;
    private static DefaultListModel modelA;
    private static final DefaultListModel modelB = new DefaultListModel();

    /**
     * Creates new form AddingTerminals
     *
     * @param owner
     * @param holdedPOS
     */
    private AddingTerminals(JDialog parent, String holdedTeminals) {
        super(parent, true);

        for (int i = 122; i < 200; i++) {
            //if (i < 99) {
            //modelB.addElement(i < 9 ? "00" + String.valueOf(i + 1) : "0" + String.valueOf(i + 1));
            //} else {
            if (Arrays.binarySearch(holdedTeminals.split(":"), i) != -1) {
                modelB.addElement(String.valueOf(i));
            }
            //}
        }

        initComponents();
    }

    protected static synchronized AddingTerminals getInstance(JDialog parent, String holdedTeminals) {
        if (instance == null) {
            instance = new AddingTerminals(parent, holdedTeminals);
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane11 = new javax.swing.JScrollPane();
        termsAddedList = new javax.swing.JList();
        addToDepButton = new javax.swing.JButton();
        remFromDepButton = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        termsAllList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(200, 2147483647));
        setMinimumSize(new java.awt.Dimension(200, 500));
        setPreferredSize(new java.awt.Dimension(200, 500));

        termsAddedList.setModel(modelA);
        termsAddedList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane11.setViewportView(termsAddedList);

        addToDepButton.setText("<");
        addToDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToDepButtonActionPerformed(evt);
            }
        });

        remFromDepButton.setText(">");
        remFromDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remFromDepButtonActionPerformed(evt);
            }
        });

        termsAllList.setModel(modelB);
        termsAllList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane13.setViewportView(termsAllList);

        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setToolTipText("");
        jLabel1.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addToDepButton)
                            .addComponent(remFromDepButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane11, jScrollPane13});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13)
                            .addComponent(jScrollPane11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(addToDepButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remFromDepButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(210, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public String showAddTerminalsDialog(String terminals) {
        modelA = new DefaultListModel();
        if (!terminals.isEmpty()) {
            for (String terminal : terminals.split(":")) {
                modelA.addElement(terminal);
            }
            terminals = "";
        }
        setVisible(true);

        for (int i = 0; i < modelA.getSize(); i++) {
            terminals += modelA.get(i) + ":";
        }

        modelA.removeAllElements();

        return terminals.substring(0, terminals.length() - 1);
    }

    private void addToDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToDepButtonActionPerformed
        int index = termsAllList.getSelectedIndex();

        if (index == -1) {
            jLabel1.setText("Выберите хотя бы одну кассу!");
        } else {
            modelA.addElement(modelB.remove(index));
        }
    }//GEN-LAST:event_addToDepButtonActionPerformed

    private void remFromDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remFromDepButtonActionPerformed
        int index = termsAddedList.getSelectedIndex();

        if (index == -1) {
            jLabel1.setText("Выберите хотя бы одну кассу!");
        } else {
            modelB.addElement(modelA.remove(index));
        }
    }//GEN-LAST:event_remFromDepButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToDepButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JButton remFromDepButton;
    private javax.swing.JList<String> termsAddedList;
    private javax.swing.JList<String> termsAllList;
    // End of variables declaration//GEN-END:variables
}
